### ISSUE TITLE
Randomize BLE MAC address each time the ephid changes

### ISSUE THREAD

**Issue by dspinellis** [eellak/epidose#12]
See OCF commands 0x0005 and 0x0006 (PDF page 1051) of the Bluetooth Core specification 4.0.

**Comment by stefanos1316** [comment]
I have searched from the official site of OCF and found only specification the 2.1.2.
However, from this [site](https://www.bluetooth.com/specifications/archived-specifications/), I downloaded
the Bluetooth core specification 4.0 and pages 1057 and 1058 contain the above-requested commands.
Are those the ones you had in mind?

**Comment by dspinellis** [comment]
In the [now current specification 5.2](https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=478726) I see this is specified on p. 2480 section 7.8.4 LE Set Random Address command with the "HCI_LE_Set_Random_Address". Section 7.8.5 LE Set Advertising Parameters command may also be relevant. We must of course use the specification that matches the drivers available on the latest Raspbian.
